export const policies={
 privacy:{title:'Privacy notice',intro:'Draft for business and jurisdiction-specific review. This notice is not an adopted privacy policy.',sections:[
 ['Current preview','The enquiry form prepares an email draft in your browser. You choose whether to open your email app and send it to info@heuresiscapital.com. The website does not submit or store form values. Research-update requests also open your email app and do not automatically subscribe you. The website does not include analytics or advertising trackers. Hosting and access providers may process technical request data under their own terms and notices.'],
 ['Proposed collection and use','When enabled, the enquiry form is intended to collect a name, email address, optional organisation and the details supplied with an enquiry. Newsletter sign-up would collect an email address and any chosen preferences. The intended purposes are to respond to enquiries and deliver requested research updates. These are proposed uses requiring review.'],
 ['Choices and marketing','An ordinary enquiry will not automatically add someone to a marketing list. Newsletter consent, if used, must be separate and freely given. A functioning unsubscribe route must be in place before marketing messages are sent.'],
 ['Information to complete before launch','Confirm the legal entity acting as controller, its contact details, applicable jurisdiction, lawful grounds, service providers, international transfers, retention periods, security measures, rights and complaint routes. Complete a hosting and cookie review. Do not enable collection until these items and the final notice have been approved.']
 ]},
 terms:{title:'Website terms',intro:'Draft terms for business and legal review. No governing law, legal entity or contractual service terms have been confirmed.',sections:[
 ['About this website','Heuresis Capital is a capital markets research firm. This website is intended to provide research content and a way to enquire about research needs. The preview edition contains clearly labelled illustrative material.'],
 ['Research context','Illustrative samples are not current investment recommendations or analyses of actual issuers. Genuine publications must explain their scope, dates, sources, assumptions and limitations. Website content is not a substitute for understanding the circumstances of a particular decision.'],
 ['Use of materials','Before public launch, confirm the ownership and licence terms for research, images, third-party data and downloads. Define permitted reuse and a rights-contact route. No paid access, account service or subscription contract is offered by this preview.'],
 ['Business review required','Complete the contracting entity, applicable law and forum, contact information, website-use rules, intellectual-property permissions, appropriate limitations and any consumer protections that apply. Any future client engagement should use separately agreed terms.']
 ]},
 'research-disclosures':{title:'Research disclosures',intro:'A proposed disclosure framework for review. It does not assert that policies have been adopted or that any actual report is free of conflicts.',sections:[
 ['Identify the publication','Each genuine report should identify its author, publication date, subsequent updates, scope, source documents and data as-of dates. A short market note can use a shorter structure where appropriate.'],
 ['Distinguish evidence and judgement','Reported facts should have sources. Estimates, assumptions, opinions and synthetic scenarios should be clearly labelled. Explain the methodology and the evidence that could change the conclusion. A chart should state its units and observation date, with an accessible data summary.'],
 ['Authorship, sponsorship and conflicts','Confirm the author, any commissioning or sponsorship arrangement, issuer review, relevant holdings, compensation or other relationships for every report. Do not infer “no conflicts” from an empty field. Define who reviews and updates these disclosures before research is published.'],
 ['Corrections and limitations','Adopt a process for material corrections and methodology changes, including an updated date where relevant. Explain source limitations, uncertainty and the boundaries of a report’s intended use.'],
 ['Status of preview samples','The sample reports were written to demonstrate website content and layout. They use no actual issuer data, current market quotations, ratings or target prices. The sample bank-earnings table and chart contain synthetic index values and are labelled beside the figure.']
 ]}
} as const;
