import { brand } from './brand';
import { capabilities } from './site-config';
import { policies } from './policies';

export type Content = { [key: string]: string | boolean | Content[] };
export type Field = { key: string; label: string; type?: 'text' | 'textarea' | 'url' | 'email' | 'image' | 'file' | 'toggle' | 'list'; fields?: Field[]; max?: number };
export type ContentDefinition = { title: string; description: string; path: string; fields: Field[]; defaults: Content };
const text = (key: string, label: string, type: Field['type'] = 'text'): Field => ({ key, label, type });
const toggle = (key: string, label: string): Field => text(key, label, 'toggle');
const list = (key: string, label: string, fields: Field[], max = 30): Field => ({ key, label, type: 'list', fields, max });
const intro = [text('eyebrow', 'Section label'), text('title', 'Heading'), text('intro', 'Introduction', 'textarea')];
const linkFields = [text('label', 'Button or link label'), text('url', 'Destination', 'url')];
const paragraphs = list('paragraphs', 'Paragraphs', [text('text', 'Paragraph', 'textarea')]);
const sections = list('sections', 'Sections', [text('title', 'Heading'), text('body', 'Text', 'textarea')]);
export const definitions: Record<string, ContentDefinition> = {
 settings: { title: 'Brand, navigation & footer', description: 'Logo, company details, navigation, search descriptions and footer links.', path: '/', fields: [text('name','Company name'),text('description','Website description','textarea'),text('logo','Logo','image'),text('email','Contact email','email'),text('phone','Phone'),text('address','Address','textarea'),text('footerText','Footer description','textarea'),text('copyright','Copyright name'),text('footerNote','Footer note'),text('accent','Accent colour (#RRGGBB)'),list('navigation','Main navigation',[...linkFields,toggle('visible','Show link')],10),list('footerLinks','Footer links',linkFields,12),list('social','Social links',linkFields,8)], defaults: {name:brand.name, description:'Considered perspectives on companies, economies and market themes.',logo:brand.logo,email:brand.email,phone:'',address:'',footerText:'Considered perspectives on companies, economies and market themes.',copyright:brand.name,footerNote:'Capital markets research',accent:'#9C8552',navigation:[{label:'Research',url:'/research',visible:true},{label:'Services',url:'/services',visible:true},{label:'About',url:'/about',visible:true},{label:'Contact',url:'/contact',visible:true}],footerLinks:[{label:'The Heuresis Brief',url:'/#newsletter'},{label:'Discuss a research project',url:'/contact?type=bespoke'}],social:[]} },
 home: { title:'Homepage',description:'Opening message, featured research, latest articles and the project enquiry section.',path:'/',fields:[...intro,text('primaryLabel','Primary button label'),text('primaryUrl','Primary button destination','url'),text('secondaryLabel','Secondary button label'),text('secondaryUrl','Secondary button destination','url'),toggle('showFeature','Show featured research panel'),text('featureLabel','Feature label'),text('featureTitle','Feature heading when no research is published'),text('featureIntro','Feature introduction','textarea'),text('featureLinkLabel','Feature link label'),text('featureLinkUrl','Feature link destination','url'),toggle('showResearch','Show latest research'),text('researchLabel','Latest research section label'),text('researchTitle','Latest research heading'),text('emptyTitle','Empty research heading'),text('emptyIntro','Empty research description','textarea'),toggle('showCoverage','Show service coverage'),toggle('showApproach','Show research approach'),toggle('showBespoke','Show project enquiry section'),text('bespokeLabel','Project enquiry label'),text('bespokeTitle','Project enquiry heading'),text('bespokeIntro','Project enquiry description','textarea'),text('bespokeButton','Project enquiry button'),text('bespokeUrl','Project enquiry destination','url')],defaults:{eyebrow:'Perspective. Evidence. Understanding.',title:'A clearer view of capital markets.',intro:'Company fundamentals. Economic forces. Structural change. Heuresis Capital brings them into focus through careful research and clear thinking.',primaryLabel:'Explore research',primaryUrl:'/research',secondaryLabel:'Discuss your research needs',secondaryUrl:'/contact?type=bespoke',showFeature:true,featureLabel:'The Heuresis perspective',featureTitle:'Good questions. Considered answers.',featureIntro:'Our first publications are in preparation. Discover the thinking behind Heuresis.',featureLinkLabel:'Our approach',featureLinkUrl:'/about',showResearch:true,researchLabel:'Ideas worth examining',researchTitle:'Latest research',emptyTitle:'The first chapter is taking shape.',emptyIntro:'Our first research publications will appear here. In the meantime, explore our purpose.',showCoverage:false,showApproach:false,showBespoke:true,bespokeLabel:'A question of your own?',bespokeTitle:'Research shaped around what you need to understand.',bespokeIntro:'From company fundamentals to a sector’s changing economics, a well-defined question is the starting point for bespoke research.',bespokeButton:'Discuss a research project',bespokeUrl:'/contact?type=bespoke'} },
 about:{title:'About page',description:'Company introduction, purpose and supporting sections.',path:'/about',fields:[...intro,text('quote','Highlighted statement','textarea'),paragraphs,sections],defaults:{eyebrow:'About Heuresis',title:'A considered perspective. A clearer understanding.',intro:'Heuresis Capital is a new capital markets research firm founded by a group of friends.',quote:'Good research gives a question the attention it deserves.',paragraphs:[{text:'Our purpose is to make companies, economies and market themes easier to understand through careful analysis and clear writing.'},{text:'We are building a research publication and a place to begin conversations about specific analytical questions.'}],sections:[]}},
 services:{title:'Services & coverage',description:'Add, edit, hide and order research services.',path:'/services',fields:[...intro,toggle('visible','Show services'),text('emptyTitle','Heading while services are hidden'),text('emptyIntro','Description while services are hidden','textarea'),list('items','Services',[text('title','Service name'),text('type','Research category'),text('short','Short description'),text('question','Description','textarea'),text('deliverable','Deliverables','textarea'),text('audience','Audience','textarea'),...linkFields,toggle('visible','Show this service')])],defaults:{eyebrow:'Research capabilities',title:'Start with the question. Build the understanding.',intro:'Focused research around the businesses, economic forces and market themes that matter to a decision.',visible:false,emptyTitle:'Our research scope is being prepared.',emptyIntro:'Confirmed capabilities will be shared here when available.',items:capabilities.map(c=>({...c,label:'Discuss this research',url:'/contact?type=bespoke&topic='+encodeURIComponent(c.title),visible:true}))}},
 approach:{title:'Research approach',description:'The research process displayed on About and optionally the homepage.',path:'/about#approach',fields:[toggle('visible','Show research approach'),...intro,sections],defaults:{visible:false,eyebrow:'The way we think',title:'Make the reasoning visible.',intro:'Define the question. Show the evidence. Explain where assumptions begin and what could change the conclusion.',sections:[{title:'Frame the question',body:'Define the decision, the context and what needs to be understood.'},{title:'Examine the evidence',body:'Look closely at sources, comparability and the gaps in the data.'},{title:'Test the assumptions',body:'Explore scenarios and the evidence that could change the view.'},{title:'Explain the implications',body:'Make the reasoning, uncertainty and conclusions clear.'}]}},
 research:{title:'Research library page',description:'Library headings and the message shown before the first publication.',path:'/research',fields:[...intro,text('emptyTitle','Empty library heading'),text('emptyIntro','Empty library description','textarea')],defaults:{eyebrow:'The research library',title:'Explore the thinking.',intro:'Perspectives that look beneath the headline. Find a question, follow the evidence, form a clearer view.',emptyTitle:'Our first publications are in preparation.',emptyIntro:'Explore the purpose behind Heuresis while we prepare our first research.'}},
 contact:{title:'Contact page',description:'Contact messages, enquiry guidance and form introduction.',path:'/contact',fields:[...intro,text('asideTitle','Guidance heading'),text('asideIntro','Guidance description','textarea'),list('prompts','Enquiry prompts',[text('text','Prompt')],10),text('formTitle','Form heading'),text('formIntro','Form description','textarea')],defaults:{eyebrow:'Begin a conversation',title:'What would you like to understand?',intro:'Share the question behind your research needs. A focused conversation is a useful place to begin.',asideTitle:'A little context goes a long way.',asideIntro:'For a bespoke research discussion, it helps to consider:',prompts:[{text:'The analytical question or decision.'},{text:'The companies, sector or market involved.'},{text:'How you intend to use the research.'},{text:'Any timing or scope constraints.'}],formTitle:'Start with your question.',formIntro:'Prepare your message below, then open it in your email app to review and send.'}},
 newsletter:{title:'Research updates section',description:'Visibility, wording and the email request button.',path:'/#newsletter',fields:[toggle('visible','Show research updates'),...intro,text('cardTitle','Request heading'),text('cardIntro','Request description','textarea'),text('button','Button label'),text('subject','Email subject')],defaults:{visible:true,eyebrow:'Stay close to the thinking',title:'The Heuresis Brief',intro:'Research and market perspectives, sent when there is something worth sharing.',cardTitle:'Be part of the conversation.',cardIntro:'Email us to express your interest in future research updates.',button:'Request updates by email',subject:'Research updates — Heuresis Capital'}},
  team:{title:'Team profiles',description:'Photos, roles, biographies, contact links and display order. Publishing access is managed separately.',path:'/about#team',fields:[toggle('visible','Show team'),...intro,list('members','Team members',[text('name','Full name'),text('role','Role'),text('bio','Biography','textarea'),text('photo','Photo','image'),text('credentials','Qualifications or credentials'),text('email','Public email (optional)','email'),text('linkedin','LinkedIn or profile link','url'),toggle('visible','Show this person')],40)],defaults:{visible:false,eyebrow:'Our people',title:'The team',intro:'',members:[]}},
  resources:{title:'Document library',description:'Publish standalone materials. Move documents up or down, replace their files, or remove old entries.',path:'/resources',fields:[toggle('visible','Show document library'),...intro,list('documents','Documents',[text('title','Document title'),text('description','Description','textarea'),text('category','Category'),text('file','File','file'),toggle('visible','Show document')],100)],defaults:{visible:false,eyebrow:'Supporting materials',title:'Documents & resources',intro:'Download research materials and reference documents.',documents:[]}},
};
for (const [key, policy] of Object.entries(policies)) definitions[key] = {title:policy.title,description:'Edit and review this page before making it visible.',path:'/'+key,fields:[toggle('visible','Show this page'),text('title','Heading'),text('intro','Introduction','textarea'),sections],defaults:{visible:false,title:policy.title,intro:policy.intro,sections:policy.sections.map(([title,body])=>({title,body}))}};
export const value = (d: Content, key: string) => typeof d[key] === 'string' ? d[key] as string : '';
export const enabled = (d: Content, key: string) => d[key] === true;
export const items = (d: Content, key: string) => Array.isArray(d[key]) ? d[key] as Content[] : [];
export const defaultWebsite = () => Object.fromEntries(Object.entries(definitions).map(([k,d])=>[k,structuredClone(d.defaults)]));
export function emptyFields(fields: Field[]): Content { return Object.fromEntries(fields.map(f=>[f.key,f.type==='toggle'?true:f.type==='list'?[]:''])); }
export function assetIds(data: unknown): string[] { const ids: string[]=[]; function walk(v:unknown){if(typeof v==='string' && /^\/assets\/[a-f0-9-]{36}$/.test(v)) ids.push(v.slice(8)); else if(Array.isArray(v)) v.forEach(walk); else if(v&&typeof v==='object') Object.values(v).forEach(walk);} walk(data);return [...new Set(ids)]; }
