export const dynamic='force-dynamic';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { site, capabilities } from '@/lib/site-config';
import { getResearch } from '@/lib/research-server';
import { ResearchRow, Newsletter, SectionLabel, Approach } from '@/components/site';
export default async function Home(){
 const reports=await getResearch(), featured=reports[0], second=reports[1]||featured;
 return <main id="main">
 <section className="container hero"><div className="hero-copy"><SectionLabel>Perspective. Evidence. Understanding.</SectionLabel><h1>A clearer view of<br/>capital markets<span className="gold">.</span></h1><p className="lead">Company fundamentals. Economic forces. Structural change. Heuresis Capital brings them into focus through careful research and clear thinking.</p><div className="actions"><Link className="button" href="/research">Explore research <ArrowRight size={17}/></Link><Link className="text-link" href="/contact?type=bespoke">Discuss your research needs <ArrowUpRight size={17}/></Link></div></div>
 <aside className="hero-feature"><div className="feature-top"><span className="eyebrow">{featured?'In focus':'The Heuresis perspective'}</span><span className="small">{featured?.status==='sample'?'Illustrative sample':'Research & ideas'}</span></div>{featured?<><div className="feature-number" aria-hidden="true">01<span>/ Research perspective</span></div><span className="eyebrow">{featured.type}</span><h2><Link href={'/research/'+featured.slug}>{featured.title}</Link></h2><p>{featured.summary}</p><Link className="text-link" href={'/research/'+featured.slug}>Read the perspective <ArrowUpRight size={18}/></Link></>:<><img className="brand-symbol" src="/symbol.svg" alt=""/><h2>Good questions.<br/>Considered answers.</h2><p>Our first publications are in preparation. Discover the thinking behind Heuresis.</p><Link className="text-link" href="/about">Our approach <ArrowUpRight size={18}/></Link></>}<div className="feature-bottom"><span>HEURESIS CAPITAL</span><span aria-hidden="true">↗</span></div></aside></section>
 <section className="research-home container section"><div className="section-heading"><div><SectionLabel>Ideas worth examining</SectionLabel><h2>Latest research</h2></div><Link className="text-link" href="/research">View all research <ArrowRight size={17}/></Link></div>{reports.length?<div className="latest-grid"><article className="latest-feature"><span className="eyebrow">{second.type}</span><h3><Link href={'/research/'+second.slug}>{second.title}</Link></h3><p>{second.summary}</p><div className="row-meta">{second.status==='sample'?'Illustrative sample':second.date} · {second.readingMinutes} min read</div><Link className="circle-link" href={'/research/'+second.slug} aria-label={'Read '+second.title}><ArrowUpRight size={21}/></Link></article><div>{reports.filter(r=>r.slug!==second.slug).slice(0,3).map(r=><ResearchRow key={r.slug} report={r} compact/>)}</div></div>:<div className="editorial-empty"><h3>The first chapter is taking shape.</h3><p>Our first research publications will appear here. In the meantime, explore our purpose.</p><Link className="text-link" href="/about">About Heuresis <ArrowRight size={16}/></Link></div>}</section>
 {(site.preview||site.capabilitiesApproved)&&<section className="warm section"><div className="container"><div className="section-heading"><div><SectionLabel>Connecting the picture</SectionLabel><h2>Research across the market</h2></div><p className="section-note">{site.preview?'Proposed research areas for review.':'Explore our research areas.'}</p></div><div className="coverage-grid">{capabilities.slice(0,4).map((c,i)=><Link className="coverage-item" href={'/research?type='+encodeURIComponent(c.type)} key={c.title}><span className="coverage-index">0{i+1}</span><h3>{c.title} <ArrowUpRight size={18}/></h3><p>{c.short}</p></Link>)}</div></div></section>}
 {(site.preview||site.approachApproved)&&<section className="container section"><div className="approach-heading"><div><SectionLabel>The way we think</SectionLabel><h2>Clarity begins with<br/>the right questions.</h2></div><div><p>From a company’s earnings to a shift in market conditions, useful research makes the reasoning visible.</p>{site.preview&&<p className="small">Our proposed editorial approach, for review.</p>}<Link className="text-link" href="/about#approach">Explore our approach <ArrowUpRight size={17}/></Link></div></div><Approach/></section>}
 <section className="bespoke-band"><div className="container bespoke-inner"><div><SectionLabel>A question of your own?</SectionLabel><h2>Research shaped around<br/>what you need to understand.</h2></div><div><p>From company fundamentals to a sector’s changing economics, a well-defined question is the starting point for bespoke research.</p><Link className="button light-button" href="/contact?type=bespoke">Discuss a research project <ArrowUpRight size={17}/></Link></div></div></section><Newsletter policiesVisible={site.preview||site.policiesApproved}/></main>;
}
