'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {ArrowUpRight,ArrowRight,Menu,Mail,Copy,Check,Printer} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {brand} from '@/lib/brand';
import type {Research} from '@/lib/research';
const nav=[['Research','/research'],['Services','/services'],['About','/about'],['Contact','/contact']];
export function Header(){
 const [open,setOpen]=useState(false);const path=usePathname();
 return <header className="site-header"><div className="container header-inner"><Link href="/" className="logo-link" aria-label="Heuresis Capital home"><img className="full-logo" src={brand.logo} width="2172" height="724" alt="Heuresis Capital"/><img className="mobile-symbol" src="/symbol.svg" width="42" height="42" alt=""/><span className="mobile-name">Heuresis<span>CAPITAL</span></span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,url])=><Link key={url} className={path.startsWith(url)?'active':''} aria-current={path===url?'page':undefined} href={url}>{label}</Link>)}<Link className="header-subscribe" href="/#newsletter">Request insights <ArrowUpRight size={15}/></Link></nav><div className="mobile-nav"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="menu-button" aria-label="Open navigation"><Menu size={24}/></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle>Heuresis</SheetTitle><SheetDescription>Capital</SheetDescription><nav aria-label="Mobile navigation">{nav.map(([label,url])=><Link key={url} href={url} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={18}/></Link>)}<Link href="/#newsletter" onClick={()=>setOpen(false)}>Request insights <Mail size={18}/></Link></nav></SheetContent></Sheet></div></div></header>;
}
export function Footer({preview,policiesVisible,contactEmail,social}:{preview:boolean;policiesVisible:boolean;contactEmail:string|null;social:{label:string;url:string}[]}){
 return <footer className="site-footer"><div className="container"><div className="footer-top"><div><Link className="footer-logo" href="/"><img src={brand.logo} width="2172" height="724" alt="Heuresis Capital"/></Link><p>Considered perspectives on companies,<br/>economies and market themes.</p></div><div className="footer-nav"><span className="eyebrow">Explore</span>{nav.map(([label,url])=><Link key={url} href={url}>{label}</Link>)}</div><div className="footer-nav"><span className="eyebrow">Stay in the conversation</span><Link href="/#newsletter">The Heuresis Brief <ArrowUpRight size={16}/></Link><Link href="/contact?type=bespoke">Discuss a research project <ArrowUpRight size={16}/></Link>{contactEmail&&<a href={'mailto:'+contactEmail}>{contactEmail}</a>}{social.map(s=><a key={s.url} href={s.url}>{s.label}</a>)}</div></div><div className="footer-bottom"><Link href="/admin">Team sign in</Link><span>© {new Date().getFullYear()} Heuresis Capital</span>{policiesVisible&&<div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/research-disclosures">Research disclosures</Link></div>}<span>{preview?'Preview edition · Draft policies':'Capital markets research'}</span></div></div></footer>;
}
export function SectionLabel({children}:{children:React.ReactNode}){return <p className="section-label"><span/>{children}</p>;}
export function ResearchRow({report:r,compact=false}:{report:Research;compact?:boolean}){
 return <article className={'research-row '+(compact?'compact':'')}><div className="row-content"><div className="row-top"><span className="eyebrow">{r.type}</span>{r.status==='sample'&&<span className="sample-label">Sample</span>}</div><h3><Link href={'/research/'+r.slug}>{r.title}</Link></h3><p>{r.summary}</p><div className="row-meta">{r.date&&<time dateTime={r.date}>{new Date(r.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})} · </time>}{r.author&&<>{r.author} · </>}{r.readingMinutes} min read{!compact&&<> · {r.topics.join(' / ')}</>}</div></div><Link className="row-arrow" href={'/research/'+r.slug} aria-label={'Read '+r.title}><ArrowUpRight size={22}/></Link></article>;
}
export function Approach(){return <div className="approach-grid">{[['Frame the question','Define the decision, the context and what needs to be understood.'],['Examine the evidence','Look closely at sources, comparability and the gaps in the data.'],['Test the assumptions','Explore scenarios and the evidence that could change the view.'],['Explain the implications','Make the reasoning, uncertainty and conclusions clear.']].map(([t,p],i)=><div key={t}><span className="step-number">0{i+1}</span><h3>{t}</h3><p>{p}</p></div>)}</div>;}
export function Newsletter({policiesVisible=true}:{policiesVisible?:boolean}){return <section className="container newsletter section" id="newsletter"><div><SectionLabel>Stay close to the thinking</SectionLabel><h2>The Heuresis Brief</h2><p>Research and market perspectives,<br className="desktop-break"/> sent when there is something worth sharing.</p></div><div className="newsletter-request"><Mail size={24} strokeWidth={1.5}/><h3>Be part of the conversation.</h3><p>Email us to express your interest in future research updates.</p><a className="button" href={'mailto:'+brand.email+'?subject='+encodeURIComponent('Research updates — Heuresis Capital')+'&body='+encodeURIComponent('Hello Heuresis Capital,\r\n\r\nPlease let me know when your research updates are available.')} >Request updates by email <ArrowUpRight size={17}/></a><p className="small">Opens your email app. This is a request, not an automatic subscription. {policiesVisible&&<Link href="/privacy">Privacy notice</Link>}</p></div></section>;}
export function ShareTools(){const[state,setState]=useState('Copy link');async function copy(){try{await navigator.clipboard.writeText(window.location.href);setState('Link copied');}catch{setState('Copy the address from your browser');}}return <div className="share-tools"><button onClick={copy}>{state==='Link copied'?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{state}</span></button><button onClick={()=>window.print()}><Printer size={16}/>Print article</button></div>;}
