export const dynamic='force-dynamic';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,Download} from 'lucide-react';
import {findResearch,getResearch} from '@/lib/research-server';
import {site} from '@/lib/site-config';
import {ResearchRow,ShareTools} from '@/components/site';
import {ScenarioChart} from '@/components/scenario-chart';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const r=await findResearch(slug);if(!r)return{title:'Research not found',robots:{index:false,follow:false}};return{title:r.title,description:r.summary,alternates:{canonical:'/research/'+r.slug},robots:r.status==='sample'||site.preview?{index:false,follow:false}:{index:true,follow:true},openGraph:{type:'article',title:r.title,description:r.summary,url:site.domain+'/research/'+r.slug}};}
export default async function Article({params}:{params:Promise<{slug:string}>}){
 const{slug}=await params,r=await findResearch(slug);if(!r)notFound();const related=(await getResearch()).filter(x=>x.slug!==slug).sort((a,b)=>Number(b.type===r.type)-Number(a.type===r.type)).slice(0,2);
 return <main id="main" className="container"><header className="article-header"><Link className="breadcrumb" href="/research"><ArrowLeft size={14}/> Research library</Link><div className="row-top"><span className="eyebrow">{r.type}</span>{r.status==='sample'&&<span className="sample-label">Illustrative sample</span>}</div><h1>{r.title}</h1><p className="lead">{r.summary}</p><div className="article-metadata">{r.author&&<span>{r.author}</span>}{r.date&&<time dateTime={r.date}>{r.date}</time>}{r.updated&&<span>Updated {r.updated}</span>}<span>{r.readingMinutes} min read</span><span>{r.topics.join(' / ')}</span></div>{r.status==='sample'&&<div className="notice">An original sample for the private preview. No actual issuer, current market data or investment recommendation. No publication date or analyst attribution is implied.</div>}<ShareTools/>{r.pdf&&<a className="text-link" href={r.pdf} download><Download size={16}/>Download report PDF</a>}</header>
 <div className="article-layout"><aside className="toc"><p>In this perspective</p><nav aria-label="Article contents">{r.sections.map(s=><a href={'#'+s.id} key={s.id}>{s.title}</a>)}<a href="#disclosures">Sources & disclosures</a></nav></aside><article className="article-body"><section className="takeaways"><h2>Three key takeaways</h2><ol>{r.takeaways.map(t=><li key={t}>{t}</li>)}</ol></section>{r.sections.map(s=><section id={s.id} key={s.id}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.chart&&<ScenarioChart/>}</section>)}<section className="supporting-materials" hidden={!r.materials?.length}><h2>Supporting materials</h2>{r.materials?.map(m=><a className="material-download" key={m.id} href={m.url} download><Download size={18}/><span>{m.name}<small>{(m.size/1024).toFixed(0)} KB</small></span></a>)}</section><section id="disclosures" className="disclosure"><h2>Sources, methodology & disclosures</h2><ul className="sources">{r.sources.map(s=><li key={s.label}>{s.url?<a href={s.url} rel="noopener noreferrer" target="_blank">{s.label}</a>:s.label}</li>)}</ul><p>{r.disclosures}</p>{(site.preview||site.policiesApproved)&&<Link className="text-link" href="/research-disclosures">Read the research disclosures</Link>}</section></article></div><section className="related"><h2>Continue exploring</h2>{related.map(x=><ResearchRow key={x.slug} report={x}/>)}</section>{r.status==='published'&&r.author&&r.date&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:r.title,datePublished:r.date,author:{'@type':'Person',name:r.author},publisher:{'@type':'Organization',name:site.name},url:site.domain+'/research/'+r.slug}).replace(/</g,'\\u003c')}}/>}</main>;
}
